version: '3.8'

services:
  app:
    build: .
    container_name: fitness-app
    ports:
      - "3000:3000"
    environment:
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - data:/app/data

volumes:
  data: